# Generated by Django 6.0.6 on 2026-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('agence', models.CharField(max_length=10)),
                ('poste', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
    ]
